# Generated by Django 4.1.7 on 2023-03-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='Course',
            new_name='course',
        ),
    ]
